# Generated by Django 4.2.16 on 2024-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "verbose_name": "Cooperations & Calls",
                "verbose_name_plural": "Cooperations & Calls",
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(default=0, max_length=11, verbose_name="شماره تلفن"),
            preserve_default=False,
        ),
    ]
